kind: ConfigMap
apiVersion: v1
data:
  dynamic.yaml: |-
    http:
      routers:
        http:
          entryPoints:
            - web
          rule: "HostRegexp(`{subdomain:.*}`)"
          service: app
        https:
          entryPoints:
            - websecure
          rule: "HostRegexp(`{subdomain:.*}`)"
          service: app
          tls: {}
      services:
        app:
          loadBalancer:
            servers:
              - url: "https://..."
metadata:
  name: dynamic